// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using apitienda.Data;

#nullable disable

namespace apitienda.Users.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251216080250_InicialUsers")]
    partial class InicialUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("apitienda.Models.Usuario", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("address_city")
                        .HasColumnType("text");

                    b.Property<string>("address_complement")
                        .HasColumnType("text");

                    b.Property<string>("address_interior_number")
                        .HasColumnType("text");

                    b.Property<string>("address_neighborhood")
                        .HasColumnType("text");

                    b.Property<string>("address_number")
                        .HasColumnType("text");

                    b.Property<string>("address_state")
                        .HasColumnType("text");

                    b.Property<string>("address_zip_code")
                        .HasColumnType("text");

                    b.Property<string>("contact_phone_number")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("date_joined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date_of_birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<bool>("email_verified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("email_verified_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_superuser")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("last_login")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("modified_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nationality")
                        .HasColumnType("text");

                    b.Property<string>("occupation")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("profile_picture")
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("apitienda.Models.token_blacklist", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("jti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("revoked_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("token_blacklist");
                });

            modelBuilder.Entity("apitienda.Models.token_blacklist", b =>
                {
                    b.HasOne("apitienda.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
